# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2eeaad70cf35753adb4ca05656e029eb8bac23d23987d0957edada9bfa1a08a136adc4ac195425cb59e94c236d9be6cd4dfc1c7f657a6dc15a75986ad8d73905

test:
  secret_key_base: 6cc286c5cbc0d840481e905b077e7f2054583272cd6df8df30f2e13de9bb6e0b581714d22ebd599649dbbe03f7034108b643be67f2739b039a527048e96d756d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
